apiVersion: v1
kind: ReplicationController
metadata:
  replicas: 1
  selector:
    app: task-monitor
spec:
  template:
    metadata:
      name: task-monitor
      labels:
        app: task-monitor
    spec:
      containers:
      - name: task-monitor
        image: yujioshima/task-monitor
        imagePullPolicy: Always
      restartPolicy: OnFailure

